[package]
name = "monochange"
version = { workspace = true }
categories = { workspace = true }
documentation = "https://docs.rs/monochange"
edition = { workspace = true }
include = [
	"src/**/*.rs",
	"src/**/*.md",
	"src/**/*.yml",
	"src/**/*.toml",
	"src/**/*.template",
	"tests/**/*.rs",
	"benches/**/*.rs",
	"Cargo.toml",
	"readme.md",
]
keywords = ["cli", "changelog", "releases", "versioning", "monorepo"]
license = { workspace = true }
readme = "readme.md"
repository = { workspace = true }
rust-version = { workspace = true }
description = "Manage versions and releases for your multiplatform, multilanguage monorepo"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }-v{ version }{ archive-suffix }"
pkg-fmt = "tgz"
bin-dir = "{ bin }{ binary-ext }"

[features]
default = ["monochange_cli/default"]
cargo = ["monochange_cli/cargo"]
npm = ["monochange_cli/npm"]
deno = ["monochange_cli/deno"]
dart = ["monochange_cli/dart"]
python = ["monochange_cli/python"]
go = ["monochange_cli/go"]
github = ["monochange_cli/github"]
gitlab = ["monochange_cli/gitlab"]
gitea = ["monochange_cli/gitea"]
forgejo = ["monochange_cli/forgejo"]
mcp = ["monochange_cli/mcp"]

[dependencies]
monochange_cli = { workspace = true }

[lints]
workspace = true
